app/endpoints/main_site/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo, Length, ValidationError

from app.models import User


class RegistrationForm(FlaskForm):

    username = StringField('Username', validators=[DataRequired(), Length(max=25, message="Username must be smaller than 25 characters")])
    email = StringField('Email', validators=[DataRequired(), Email(), Length(max=50, message="Email address must be smaller than 50 characters")])
    password = PasswordField('Password', validators=[DataRequired(), Length(max=25, message="Password must be smaller than 50 characters")])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password', message="Passwords don't match")])
    submit = SubmitField('Register')

    def validate_username(self, username):

        user = User.query.filter_by(username=username.data).first()

        if user is not None:

            raise ValidationError("Username already exists. Please use a different one.")
    
    def validate_email(self, email):

        user = User.query.filter_by(email=email.data).first()
        
        if user is not None:

            raise ValidationError("Email address already exists. Please use a different one.")

class LoginForm(FlaskForm):

    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')

class GuestForm(FlaskForm):
    
    submit = SubmitField('Sign In')

app/endpoints/main_site/__init__.py
from flask import Blueprint

main_site = Blueprint("main_site", __name__, template_folder="templates")

from app.endpoints.main_site import views

app/endpoints/main_site/views.py
import os

from flask import flash, redirect, render_template, request, url_for
from flask_login import current_user, login_user
from werkzeug.urls import url_parse

from app import db, project_path
from app.endpoints.main_site import main_site
from app.endpoints.main_site.forms import GuestForm, LoginForm, RegistrationForm
from app.global_variables import GUEST
from app.utils import user_already_logged_in
from app.models import User                 

# IF THE USER IS LOGGED IN AND THEN IT CLICKS THE BACK PAGE BUTTON IT CAN GO TO LOGIN. THEN IT WILL BE REDIRECT 
# WHEN YOU CLICK "SIGN IN" OR "HOME"

@main_site.route('/', methods=["GET", "POST"])
def index():

    return redirect(url_for('main_site.login'))

@main_site.route('/login', methods=["GET", "POST"])
def login():

    if user_already_logged_in(current_user):

        return redirect(url_for('user_profile.profile', username=current_user.username))
    
    form = LoginForm()
    if form.validate_on_submit():

        user = User.query.filter_by(username=form.username.data).first()
        
        if user and user.check_password(form.password.data):

            login_user(user, remember=form.remember_me.data)
            # Redirect when the user got here from typing an URL that requires a login
            next_page = request.args.get('next')
            # If user got here directly from login, set next to their profile
            if not next_page or url_parse(next_page).netloc != '':

                next_page = url_for('user_profile.profile', username=user.username)

            return redirect(next_page)
        
        else:

            flash("Invalid username or password")
    
    guestForm = GuestForm()

    return render_template("main_site/login.html", form=form, guestForm=guestForm)

@main_site.route('/guest_login', methods=["GET", "POST"])
def guest_login():

    # Handle logged in users that type this URL
    if user_already_logged_in(current_user):

        return redirect(url_for('user_profile.profile', username=current_user.username))
    
    guestForm = GuestForm()
    if guestForm.validate_on_submit():

        user = User.query.filter_by(username=GUEST).first()
        login_user(user)

        return redirect(url_for('run.kat_upload'))

    form = LoginForm()

    return render_template("main_site/login.html", form=form, guestForm=guestForm)

@main_site.route('/register', methods=["GET","POST"])
def register():
    
    if user_already_logged_in(current_user):

        return redirect(url_for('user_profile.profile', username=current_user.username))

    form = RegistrationForm()
    if form.validate_on_submit():

        # Add user to database
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
    
        # Create user folder
        user_folder = os.path.join(project_path, form.username.data)

        if not os.path.isdir(user_folder):

            os.mkdir(user_folder)

        flash("Registration complete. Welcome to KAT!")
        
        return redirect(url_for("main_site.register"))

    return render_template("main_site/register.html", form=form)

@main_site.route("/about", methods=["GET"])
def about():
    
    return render_template("main_site/about.html", guest=GUEST)

app/endpoints/main_site/templates/main_site/about.html
{% extends "base.html" %}
{% block content %}

<h2>About KAT</h2>

<p>
	The Kmer Alignment Tool takes DNA genome sequences, choppes them up into kmers, and then aligns those kmers to Reference DNA files. 
	For the alignment it uses a combination of Suffix Arrays and the Burrows-Wheeler Transform.
</p>
<h2>Use</h2>
<p>
	If you sign is as a Guest, the result files will be uploaded to the webpage after the program is finished. 
	Once you start a run, do not close the page or you won't be able to access your results.
	<br>
	If you Register, then you will have access to your user profile where all your runs will be saved. 
	You can close the page after starting a run and the results will be uploaded to your profile once the run is finished.
	<br>
	You can only have one run at the time, otherwise you will get some funny results.
</p>


<h2>Input</h2>
<p>KAT requires 4 inputs:</p>
<ul> 
	<li><span class="bolded">Project name:</span> Name of the run</li>
	<li><span class="bolded">Kmer size:</span> This should be an integer between 5 and 1000. It represents the number of basepairs for chopping up the samples.</li>
	<li><span class="bolded">Sample file:</span> Up to 5 genome DNA sequences in fasta files. These are the samples that will be chopped into kmers.</li>
	<li><span class="bolded">Reference file:</span> Up to 5 genome DNA sequences in fasta files for the alignment.</li>
</ul>
<p>For the fasta files, the program can handle genomes with more than one sequence(e.g. chromosomes and contigs).</p>
<h2>Results</h2>
<p>A zip file can be downloaded that will include the following:</p>
<ul>
	<li><span class="bolded">Alignment table:</span> Contains the hits and hit percentages.</li>
	<img class="image" src="{{ url_for('static', filename='images/table_example.jpg') }}" alt="Result table example">
	<li><span class="bolded"> Plots of hits and hit percentages.</span></li>
	<li><span class="bolded">Alignment textfiles:</span> A .txt file is created for each sample-reference pair. 
		The file includes a list of the kmer sequences (from the sample) and their positions in the reference genome.
		In the example, kmer AAACTGGGCAGCAGGGCGGG is found in Reference NZ_CP055292.1 sequence 0, position 3383183.</li>
		<img class="image" src="{{ url_for('static', filename='images/textfile_example.jpg') }}" alt="Result textfile example">
</ul>

{% endblock%}

app/endpoints/main_site/templates/main_site/login.html
{% extends "base.html" %}
{% block content %}

<p>
	Registration is not required, but it helps you keep track of your runs and saves the results for future access. 
	Alternative you can run as a guest but the results won't be saved after you close the website. 
	Click <a href="{{url_for('main_site.register')}}" class="bolded">here</a> to register.
</p>
<div class="flex-display">
	<div class="column border">
		<form action="{{ url_for('main_site.login') }}" method="POST" novalidate>
			{{ form.hidden_tag() }}
			<h2>Login:</h2>
			<p>
				{{ form.username.label }}<br>
				{{ form.username(size=50) }}<br>
				{% for error in form.username.errors %}
					<span class="error-message">[{{ error }}]</span>
				{% endfor %}
			</p>
			<p>
				{{ form.password.label }}<br>
				{{ form.password(size=50) }}<br>
				{% for error in form.password.errors %}
					<span class="error-message">[{{ error }}]</span>
				{% endfor %}
			</p>
			<p>
				{{ form.remember_me() }} {{ form.remember_me.label }}
			</p>
			{% for message in get_flashed_messages() %}
				<span class="error-message">{{ message }}</span>
			{% endfor %}
			<p>{{ form.submit(class_="btn") }}</p>
		</form>
	</div>
	<div class="column border">
		<form action="{{ url_for('main_site.guest_login') }}" method="POST" novalidate>
				{{ form.hidden_tag() }}
				<h2>Sign in as Guest:</h2>
				<p>{{ form.submit(class_="btn") }}</p>
		</form>
	</div>
</div>

{% endblock %}

app/endpoints/main_site/templates/main_site/register.html
{% extends "base.html" %}
{% block content %}

<div class="border">
	<form action="{{url_for('main_site.register')}}" method="POST" novalidate>
		{{ form.hidden_tag() }}
		<h2>User Registration:</h2>
		<p>
			{{ form.username.label }}<br>
			{{ form.username(size=50) }}<br>
			{% for error in form.username.errors %}
			<span class="error-message">[{{ error }}]</span>
			{% endfor %}
		</p>
		<p>
			{{ form.email.label }}<br>
			{{ form.email(size=50) }}<br>
			{% for error in form.email.errors %}
			<span class="error-message">[{{ error }}]</span>
			{% endfor %}
		</p>
		<p>
			{{ form.password.label }}<br>
			{{ form.password(size=50) }}<br>
			{% for error in form.password.errors %}
			<span class="error-message">[{{ error }}]</span>
			{% endfor %}
		</p>
		<p>
			{{ form.confirm_password.label }}<br>
			{{ form.confirm_password(size=50) }}<br>
			{% for error in form.confirm_password.errors %}
			<span class="error-message">[{{ error }}]</span>
			{% endfor %}
		</p>
		<p>{{ form.submit(class_="btn") }}</p>
	</form>

	{% for message in get_flashed_messages() %}
		<h2>{{ message }}</h2>
	{% endfor %}
</div>

{% endblock %}